# Generated by Django 4.2 on 2023-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='point',
            name='visibility',
            field=models.CharField(default='Privat', max_length=50),
        ),
    ]
