# Generated by Django 4.2 on 2023-05-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_alter_point_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('name', 'description', 'lat', 'lon')},
        ),
    ]
